---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - update
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates
  - zonedisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates/finalizers
  - zonedisruptionbudgets/finalizers
  verbs:
  - update
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates/status
  - zonedisruptionbudgets/status
  verbs:
  - get
  - patch
  - update
